#!/bin/bash
# Post-installation script for rmd package

set -e

# Create symlink (if not using install file)
if [ -f /usr/local/bin/rmd.sh ] && [ ! -f /usr/local/bin/rmd ]; then
    ln -sf /usr/local/bin/rmd.sh /usr/local/bin/rmd
fi

# Install bash completion
if [ -d /etc/bash_completion.d ] && [ -f /usr/local/share/rmd/rmd.bash-completion ]; then
    cp /usr/local/share/rmd/rmd.bash-completion /etc/bash_completion.d/rmd
fi

# Update man database
if command -v mandb >/dev/null 2>&1; then
    mandb >/dev/null 2>&1 || true
fi

#DEBHELPER#

exit 0
